### ISSUE TITLE
`cf drains` shows metric registrar services

### ISSUE THREAD

**Issue by kitemongerer** [cloudfoundry/cf-drain-cli#16] opened 2018-10-15 14:58 UTC
```
cf drains
App                       Drain                                   Type      URL
metric-registrar-monitor  metric-registrar-smoke-test-structured  Logs      structured-format://DogStatsD
metric-registrar-monitor  metric-registrar-smoke-test-prom        Logs      metrics-endpoint://metrics
```

**Comment by jtuchscherer** [comment] 2018-11-19 17:47
@kitemongerer I think this is working as intended. We need to let our users know that this is a drain that will be affected by the commands offered by the `space-drain` cli, e.g. the `delete-drain-space` command.

**Comment by jtuchscherer** [comment] 2018-11-19 17:47
I am closing this for now, if you have a strong feeling that this should be handled differently, please let me know.

**Closed by jtuchscherer** 2018-11-19 17:47 UTC
Labels: scheduled
